### ISSUE TITLE
False ERROR:3 on instance_type with modules using.

### ISSUE THREAD

**Issue by Nklya** [wata727/tflint#104]
Hello.

I've found false error reporting on instance_type when use modules.
Test repo https://github.com/Nklya/tflint-example

TFLint version 0.3.4

> tflint-example  tflint
./modules/test1/main.tf
        NOTICE:1 "iam_instance_profile" is not specified. If you want to change it, you need to recreate instance. (Only less than Terra
form 0.8.8)
        ERROR:3 "${var.instance_type}" is invalid instance type.
Result: 2 issues  (1 errors , 0 warnings , 1 notices)

However, instance_type correctly set in variables.tf, modules/test1/variables.tf and terraform successfully apply this configuration.

**Comment by wata727** [comment]
I appreciate the example 🙏 
I understood this bug. I will fix it soon.

**Comment by wata727** [comment]
@Nklya TFLint v0.3.5 has been released. This bug has been fixed in this version. Please try it!

**Comment by Nklya** [comment]
Yes,  v0.3.5 works fine with all my projects.
Thanks!
