### ISSUE TITLE
Support for terraform.env variable

### ISSUE THREAD

**Issue by nanoz** [wata727/tflint#109]
terraform.env is not recognised as a valid terraform variable.

```
$ tflint
1:3: unknown variable accessed: terraform.env
$ tflint -v
TFLint version 0.3.5
```

**Comment by wata727** [comment]
Thanks for your request. I'm going to support other interpolation syntaxes including this.
By the way, can you tell me how to use `${terraform.env}` in your templates?

**Comment by nanoz** [comment]
I'm not sure what you mean by templates? I mainly use ` ${terraform.env}` as an Environment tag value and name prefix.

**Comment by AntonsKalcevs** [comment]
Hi, I have a similar issue:
```
$ tflint
1:3: unknown variable accessed: var.keyname
$ tflint -v
TFLint version 0.4.2
```
In the .tf file:
```
...
module "gocd" {
    ...
    ... 
    keyname = "${var.keyname}"
}
...
```

**Comment by wata727** [comment]
@AntonsKalcevs I think your problem is caused by being unable to find references to normal variables.
How is the `keyname` variable defined?

**Comment by AntonsKalcevs** [comment]
> How is the keyname variable defined?

`variable "keyname" {}`
