### ISSUE TITLE
[Question] Is there a way to verify which terraform variables aren't being used?

### ISSUE THREAD

**Issue by jason-riddle** [wata727/tflint#135]

**Comment by wata727** [comment]
Unfortunately, there is no such feature...

**Comment by jason-riddle** [comment]
Just thinking out loud, but do you know what might be required in order to do this?

**Comment by wata727** [comment]
Yes, but that is not a good way given the current TFLint design. In addition, I don't feel strongly the need for this feature.
Unlike web applications, you can easily delete variables. Even if there is a problem, you can notice that when doing `terraform plan`. I believe that is enough.

**Comment by jason-riddle** [comment]
Fair enough.
