### ISSUE TITLE
[Question] Which files produced the lint error?

### ISSUE THREAD

**Issue by jason-riddle** [wata727/tflint#136]
Running `tflint` on it's own does not give too much feedback at the moment.

```bash
$ tflint
1:3: unknown variable accessed: var.aws_allowed_account_ids
```

I'd like to know more specifically which files were inspected, so I've wrapped this command like so

```bash
find . -type f -not \( -path '*/.terraform/*' \) -name '*.tf' -exec \
  /bin/bash -c "echo 'Linting {}' && tflint {} --deep --error-with-issues" \;
Linting ./main.tf
1:3: unknown variable accessed: var.aws_region
Linting ./output.tf
Awesome! Your code is following the best practices :)
Linting ./variables.tf
Awesome! Your code is following the best practices :)
```

but by linting one file at a time, it has no knowledge of the other files. So, is there a way to add more information about what was linted and which file is causing issues?

**Comment by wata727** [comment]
In order to see detailed execution logs, you can use the `--debug` option.
I think this error message is insufficient to solve your problem. If you know the cause of this problem, can you tell me? I would like to consider whether it can be improved to a more understandable error message.

**Comment by jason-riddle** [comment]
I don't need to see detailed logs, It's just that it's not clear from this message

```tf
1:3: unknown variable accessed: var.aws_allowed_account_ids
```

what file it is referring to since I have multiple files.

**Comment by wata727** [comment]
Oh, sorry, I was a misunderstanding.
Unfortunately, there is currently no way to check which file is causing the error. But, as you say, I think it is not clear.
