### ISSUE TITLE
Remove dependency in brew package

### ISSUE THREAD

**Issue by myoung34** [wata727/tflint#140]
its common to use [tfenv](https://github.com/kamatama41/tfenv) to manage terraform, `$ brew install tfenv` instead of just installing terraform versions

the brew package for tflint has a dependency on terraform: 

```
$ brew install tflint
==> Installing tflint from wata727/tflint
==> Installing dependencies for wata727/tflint/tflint: go, glide, terraform
==> Installing wata727/tflint/tflint dependency: go
==> Downloading https://homebrew.bintray.com/bottles/go-1.9.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring go-1.9.sierra.bottle.tar.gz
==> Caveats
A valid GOPATH is required to use the `go get` command.
If $GOPATH is not specified, $HOME/go will be used by default:
  https://golang.org/doc/code.html#GOPATH

You may wish to add the GOROOT-based install location to your PATH:
  export PATH=$PATH:/usr/local/opt/go/libexec/bin
==> Summary
🍺  /usr/local/Cellar/go/1.9: 7,639 files, 293.7MB
==> Installing wata727/tflint/tflint dependency: glide
==> Downloading https://homebrew.bintray.com/bottles/glide-0.12.3.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring glide-0.12.3.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/glide/0.12.3: 6 files, 10MB
==> Installing wata727/tflint/tflint dependency: terraform
Error: Cannot install terraform because conflicting formulae are installed.
  tfenv: because tfenv symlinks terraform binaries

Please `brew unlink tfenv` before continuing.

Unlinking removes a formula's symlinks from /usr/local. You can
link the formula again after the install finishes. You can --force this
install, but the build may fail or cause obscure side-effects in the
resulting software.
```

**Comment by wata727** [comment]
@myoung34 Oh, sorry. Unfortunately, I'm not familiar with brew package. I will investigate, but if you have a good suggestion, please send me a patch :)
https://github.com/wata727/homebrew-tflint

**Comment by hakamadare** [comment]
`terraform` is a recommended dependency for `tflint`. you can skip a recommended dependency like so:

```sh
$ brew install --without-terraform tflint
```

i use tfenv on my own system and this is how i install it.

**Comment by myoung34** [comment]
TIL

Also though most should work out of the box, would it not be better to put `optional` for both `tfenv` and `terraform` so that it doesnt require any additional knowledge?

I dont mind adding --without, just a weird extra step since tfenv is more common in the package management circles

**Comment by hakamadare** [comment]
i agree that it’s a bit odd ☺️ i will update the documentation!

i was trying to balance “do something that works as simply as possible” with “be flexible enough to support multiple workflows”.
