### ISSUE TITLE
Question - Is it possible to ignore rules by resource/file?

### ISSUE THREAD

**Issue by shauns** [wata727/tflint#142]
The config settings for ignoring rules seem to be per-project. Is it possible to ignore rules per-file or per-resource?

I have a set of existing resources that break some of the recommendations -- I'd like to catch if I _add_ something that breaks these, but thats hard to spot with the baseline noise that comes from the existing resources.

**Comment by wata727** [comment]
Unfortunately, it cannot ignore only specific files or resources...
I have not thought of a good way yet, but I think that it must be able to set more detailed settings.

**Comment by wata727** [comment]
Hi @shauns, I'm sorry for the late reply.

In v0.8.1, ignore annotations are available for suppressing issues on the specific lines. The following is an example:

```hcl
resource "aws_instance" "foo" {
    # tflint-ignore: aws_instance_invalid_type
    instance_type = "t1.2xlarge"
}
```

Please see the [README](https://github.com/wata727/tflint/blob/v0.8.1/README.md#rules) for details.  Thank you for your question!
