### ISSUE TITLE
Valid map lookups cause evaluation errors

### ISSUE THREAD

**Issue by joestump** [wata727/tflint#157]
I've got some HCL code that looks like this:

```hcl
subnet_cidr_blocks = "${var.subnet_cidr_blocks["staging1"]}"
```

`var.subnet_cidr_blocks` is a map of lists with assigned CIDR blocks. It looks like this:

```hcl
variable "subnet_cidr_blocks" {
  description = "Two subnets per environment"
  type        = "map"

  default = {
    production = ["10.0.7.0/24", "10.0.8.0/24"]
    staging1   = ["10.0.9.0/24", "10.0.10.0/24"]
  }
}
```

When I run `tflint` I get the following error:

```
Evaluation error: 1:31: unknown variable accessed: staging1 in staging1.tf:9
```

The only thing that works is `lookup()`, but you can't use that function on maps of lists. Only maps of strings.

**Comment by wata727** [comment]
Oops, I noticed that I made a very basic mistake.
I will fix this problem soon and release the fixed version.
