### ISSUE TITLE
tflint crashes when .tflint.hcl is empty

### ISSUE THREAD

**Issue by mordant23** [wata727/tflint#165]
This may be an edge case. When I did a quick test with tflint, I got a panic output. I had created `.tflint.hcl` but did not populate it. There's no panic if the file exists. There is also no panic if the file exists but only has an empty `config` block.

The panic output is
```bash
Panic: runtime error: index out of range
 -> 0: main.main.func1: /main.go(17)
 -> 1: runtime.call16: /asm_386.s(559)
 -> 2: runtime.gopanic: /panic.go(491)
 -> 3: runtime.panicindex: /panic.go(28)
 -> 4: github.com/wata727/tflint/config.(*Config).LoadConfig: /config.go(51)
 -> 5: main.(*CLI).setupConfig: /cli.go(150)
 -> 6: main.(*CLI).Run: /cli.go(85)
 -> 7: main.main: /main.go(30)
 -> 8: runtime.main: /proc.go(185)
 -> 9: runtime.goexit: /asm_386.s(1635)

TFLint crached... :(
Please attach an output log, describe the situation and version that occurred and post an issue to https://github.com/wata727/tflint/issues
```
Just noticed a misspelling in "crached". It should be "crashed."

**Comment by wata727** [comment]
Oh, thanks for the feedback.
I will fix this bug asap. 

> Just noticed a misspelling in "crached". It should be "crashed."

😅
