### ISSUE TITLE
Different results when specifying tf files

### ISSUE THREAD

**Issue by laura-herrera** [wata727/tflint#169]
The documentations states that we can run tflint inside any folder where terraform runs, without specifying any template.
Then when I give *.tf as a parameter, I get very different results:

stg$ tflint
cluster.tf
        WARNING:2 Module source "git::ssh://git@github.com/repo/modules.git//cluster" is not pinned (terraform_module_pinned_source) 
service.tf
        WARNING:2 Module source "git::ssh://git@github.com/repo/modules.git//service" is not pinned (terraform_module_pinned_source)
network.tf
        WARNING:2 Module source "git::ssh://git@github.com/repo/modules.git//network" is not pinned (terraform_module_pinned_source)

==========
stg$ tflint *.tf
Evaluation error: 1:3: unknown variable accessed: var.region in cluster.tf:42

**Comment by wata727** [comment]
Until now, TFLint did not support globs. (It is available in the next release)
Perhaps `*.tf` is assumed to specify a single `.tf` file. Please check the log with `-d`.
