### ISSUE TITLE
Update iam_instance_profile notice according to current status

### ISSUE THREAD

**Issue by netflash** [wata727/tflint#176]
In some circumstances it says

```
NOTICE:36 "iam_instance_profile" is not specified. If you want to change it, you need to recreate the instance. (aws_instance_not_specified_iam_profile)
```

which was true back in the days.

AWS changed the behavior on 2017-FEB-09, see [blog post](https://aws.amazon.com/blogs/security/new-attach-an-aws-iam-role-to-an-existing-amazon-ec2-instance-by-using-the-aws-cli/) for details.

**Comment by wata727** [comment]
Thanks @netflash, BTW, TFLint already ignore this issue when settings `terraform_version` properly.
https://github.com/wata727/tflint/blob/v0.5.4/docs/aws_instance_not_specified_iam_profile.md#why

However, since many users already use Terraform v0.8.8 or more, this issue will be removed from next release. Thank you!

**Comment by netflash** [comment]
Totally missed the `config.hcl` feature.
Didn't test it yet. But I have a question from the first glance - should it be more convenient to get terraform version from the general terraform folder [configuration](https://www.terraform.io/docs/configuration/terraform.html) ?
e.g.
```
terraform {
  required_version = "~> 0.11.3"

  backend "s3" {
    bucket         = "my-state-storage-bucket"
    key            = "state/1/2/3/4/somefile.tfstate"
    region         = "us-west-2"
    dynamodb_table = "my-dynamo-table-for-state-storage"
  }
}
```

If you think it's a good idea, propose to move this discussion to a separate issue.
Your call.
