### ISSUE TITLE
rule to require explicit provider

### ISSUE THREAD

**Issue by sean-abbott** [wata727/tflint#178]
I've been working in an environment that sometimes requires multiple providers in a single module. Because of this, we rely fairly heavily on ensuring every resource has an explicit provider set.

Is there any chance we could add a linting rule that enforces this?

Thanks!

sean

**Comment by wata727** [comment]
I have opened a pull request in the past, but because I did not get any reaction, this issue closes.

If you still want this rule, please reopen the issue :)
