### ISSUE TITLE
tflint fails on modules if `terraform init` isn't ran

### ISSUE THREAD

**Issue by Stretch96** [wata727/tflint#198]
We use Terrafile to manage our external modules, so our module source is a relative directory:

```
module "thing" {
  source = "../vendor/terraform_modules/thing"
}
```

When running tflint, we get the error:

```
ERROR: module `../vendor/terraform_modules/thing` not found. Did you run `terraform get`?
```

The `../vendor/terraform_modules/thing` directory does exist (with all the module files)

Running `terraform init`, then `tflint` does work.

The issue is that we would like to run `tflint` in CI, without running `terraform init`, because we would then need to give CI access to the terraform state (which we have as an S3 backend)

**Comment by Stretch96** [comment]
Or I could just run `terraform get` 🙈

**Comment by wata727** [comment]
Module inspection is now disabled by default in v0.9.0. In the case, you can run TFLint without running `terraform init`. Thank you.
