### ISSUE TITLE
m5.large" is invalid instance type

### ISSUE THREAD

**Issue by tjonesmi** [wata727/tflint#203]
tflint is returning the following error for aws instance of type m5.large
ERROR:13 "m5.large" is invalid instance type. (aws_instance_invalid_type)

AWS now has these additional instance types:
-----------------------------------------------
m5.large 
m5.xlarge
m5.2xlarge
m5.4xlarge
m5.12xlarge
m5.24xlarge

**Comment by wata727** [comment]
Thanks @tjonesmi,
TFLint depends on [ec2-instances-info](https://github.com/cristim/ec2-instances-info) for listing instance types. But, I didn't upgrade it.

I updated the list of instance types and released v0.7.0.

**Comment by tjonesmi** [comment]
Looks good.  Thanks for the quick response.
