### ISSUE TITLE
Config file not picking up variables

### ISSUE THREAD

**Issue by alepeltier** [wata727/tflint#212]
Hello, 

I'm new to tflint I've installed it in my project and created a .tflint.hcl file inside this file I've defined my config with the tfvars file I'd like to use. However, when I run tflint --debug it looks like it is looking for a terraform.tfvars file.

Am I doing something wrong ?

My Config file:
`config {
  terraform_version = "0.11.7"
  deep_check = true

  aws_credentials = {
    profile = "default"
    region  = "eu-west-1"
  }

  varfile = ["dev.tfvars"]
}`

The output
`DEBUG:/loader.go:121 [INFO] Load environment...
DEBUG:/loader.go:129 [ERROR] open .terraform/environment: no such file or directory
DEBUG:/loader.go:132 [INFO] Load tfstate...
DEBUG:/loader.go:136 [ERROR] stat terraform.tfstate: no such file or directory
DEBUG:/loader.go:142 [INFO] Remote state detected
DEBUG:/loader.go:162 [INFO] Load tfvars...
DEBUG:/loader.go:165 [INFO] Load `terraform.tfvars`
DEBUG:/loader.go:167 [ERROR] stat terraform.tfvars: no such file or directory
DEBUG:/loader.go:165 [INFO] Load `dev.tfvars`
DEBUG:/loader.go:192 [INFO] Load HCL file: `dev.tfvars`
DEBUG:/loader.go:192 [INFO] Load HCL file: `component-account.tf`
DEBUG:/loader.go:60 [INFO] Load HCL file: `component-account.tf``

Also would you be able to add explain what the rule section of the hcl file is for I'm unable to find any information on the README 

Thanks in advance for any help you can give

**Comment by wata727** [comment]
Hi @alepeltier, Thanks for your feedback and question.

It's intended behavior. TFLint loads `terraform.tfvars` by default because of Terraform loads it automatically. See also https://www.terraform.io/intro/getting-started/variables.html#from-a-file

> Also would you be able to add explain what the rule section of the hcl file is for I'm unable to find any information on the README

Good suggestion. I will work on this. Thanks!

**Comment by alepeltier** [comment]
@wata727 

Thank you for your quick response.

Do you have any idea why I'm getting this error 

`Evaluation error: 4:17: unknown variable accessed: module.s3_credentials_bucket.bucket_name in component-common.tf:31`

Is it becuase I'm referencing a module ?

**Comment by wata727** [comment]
Yes, it seems to eval an expression including module attributes. it may be a bug. See also https://github.com/wata727/tflint/issues/204
Would you please paste the line 31 of `component-common.tf`?

**Comment by alepeltier** [comment]
Of course I’m away from my laptop at the moment I’ll send the code as soon as I’m back

**Comment by alepeltier** [comment]
```
  lambda_environment_variables = "${merge(
    var.common_lambda_environment_variables,
    map( 
```

**Comment by wata727** [comment]
Thanks for your report. Maybe this is the known problem.
Is this a declaration inside a module? If so, as a workaround, you can use `ignore_module` to avoid this problem. See also https://github.com/wata727/tflint/issues/167#issuecomment-385188499

**Comment by alepeltier** [comment]
Yes it is inside a module. Thank you I'll add `ignore_module` to get around this. Do you know if there is a plan to implement linting of modules?

**Comment by wata727** [comment]
Yes. I'm working on refactoring TFLint, which will fix some known bugs (including this). After that, it become able to check resources inside a module in this case.

**Comment by alepeltier** [comment]
Not a problem thank you very much for all your help
