### ISSUE TITLE
Bug: Tflint does not know fqdn attribute from aws_route_53 resource

### ISSUE THREAD

**Issue by Junkern** [wata727/tflint#234]
According to the documentation (https://www.terraform.io/docs/providers/aws/r/route53_record.html) there is an `fqdn` attribute: https://www.terraform.io/docs/providers/aws/r/route53_record.html#fqdn

When using `tflint` on a file that has this attribute it says  `Evaluation error: 1:3: unknown variable accessed`

**Comment by wata727** [comment]
I just released TFLint v0.8.0. Please try the latest version again. If you still have problems, please open a new issue instead of reopening.
