### ISSUE TITLE
List of features in README (or somewhere)

### ISSUE THREAD

**Issue by odinho** [wata727/tflint#236]
There is no easy way to see what this project do and do not do/check. Like what plugins exist if this were eslint. A bullet-point list would be helpful.

(I was specifically looking for inline JSON linting, as it's hard to not mess JSON up).

**Comment by wata727** [comment]
Hi @odinho,

A list of features is available [here](https://github.com/wata727/tflint/tree/master/docs). I guess that the list is too long in the README, so it only has a link. I don't know if this is appropriate...

**Comment by odinho** [comment]
Great thanks!

I've added a potential PR.
