### ISSUE TITLE
Generate and share sha256 checksums and GPG keys 

### ISSUE THREAD

**Issue by 211217613** [wata727/tflint#252]
WOuld like to verify security and integrity of the binaries/downloaded files. Could you provide sha256checksum and signing keys. 

Thanks!!!

**Comment by wata727** [comment]
Hi @211217613, sorry for the late reply.

I just published v0.8.0 release and add checksums and signatures. Please see [the latest release](https://github.com/wata727/tflint/releases/tag/v0.8.0) for details.

Unfortunately, I'm not familiar with GPG, so this may not be enough. In that case, let me know what is wrong. Thanks again!
