### ISSUE TITLE
Add aws_launch_configuration resource check

### ISSUE THREAD

**Issue by yevgen87** [wata727/tflint#253]
tflint does not validate aws_launch_configuration resource, which is usually used in environment configuration:
- used ami
- instance type
- instance_profile

**Comment by krzyzakp** [comment]
Was bit annoyed by this as well, so made those checks, verified that works for instance_type and submitted PR.

**Comment by wata727** [comment]
v0.8.3 has been released.
https://github.com/wata727/tflint/releases/tag/v0.8.3
