### ISSUE TITLE
Documentation request: how to add new rules

### ISSUE THREAD

**Issue by jeznag** [wata727/tflint#264]
It would be really helpful to add a section to the documentation on how to add new detectors. I'm trying to figure it out by reading the code but don't find it that intuitive.

**Comment by wata727** [comment]
Hi @jeznag, thanks for opening the issue. I think that is a good idea.
I'm currently making a major change in [this pull request](https://github.com/wata727/tflint/pull/209), and I will write a developer's guide once this is done.

**Comment by wata727** [comment]
Hi @jeznag, I just published [developer's guide](https://github.com/wata727/tflint/blob/master/docs/DEVELOPING.md). I'm looking forward to hear your feedbacks!
