### ISSUE TITLE
TFLint crashes with Panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by aburns1403** [wata727/tflint#295]
[TFLint.log](https://github.com/wata727/tflint/files/3228650/TFLint.log)

TFLint crashes when I try to run it.  Log is attached.

TFLint Ver. 0.8.0
Terraform 0.12.0

**Comment by kjagiello** [comment]
I'm experiencing the exact same error. The rule that fails is the `aws_route_not_specified_target` and it is crashing on the following resource definition:

```hcl
resource "aws_route" "internet_access" {
  route_table_id         = aws_vpc.default.main_route_table_id
  destination_cidr_block = "0.0.0.0/0"
  gateway_id             = aws_internet_gateway.default.id
}
```

**Comment by wata727** [comment]
Thank you both, this is definitely a bug.
I'm going to fix ASAP and release a new version.

**Comment by wata727** [comment]
v0.8.1 has been released. Please try this!

**Comment by aburns1403** [comment]
That seems to be working, thank you!!
