### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by Moulick** [wata727/tflint#354]
Hi,
Does tflint require terraform? I mean, I looked into the docker image and didn't find the terraform binary inside.
So, is terraform even a requirement for tflint?

**Comment by Moulick** [comment]
@wata727

**Comment by wata727** [comment]
No, even if Terraform is not installed, you can do the inspection with TFLint only.

However, if you want to inspect module calls, you need to run `terraform init` beforehand. See https://github.com/wata727/tflint/blob/v0.9.0/docs/guides/advanced.md#module-inspection

**Comment by Moulick** [comment]
Yes, Thank you! So in CI, we can `terraform init` and then just pass it as a cache to tflint without actually having `terraform`
