### ISSUE TITLE
Versions 0.10.3+ are dynamically linked and won't execute on Alpine Linux

### ISSUE THREAD

**Issue by craigfurman** [wata727/tflint#430]
Since release v0.10.3, the tflint binaries will not exec on Alpine Linux. 

The output of `file` indicated that the later binaries are dynamically linked, whereas the older binaries were statically linked:

```
alpine:/home/vagrant# file tflint-0.10.1
tflint-0.10.1: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=wXDZGwYicCpMJ-mp0H8d/FSq0FZC7mFhGqpsFBQV6/BECcCMq73DebIgvls_jj/Wa6n4j3PZSDUInAQTZx0, stripped

alpine:/home/vagrant# file tflint-0.11.0
tflint-0.11.0: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, Go BuildID=SmggEpgmnwiwAmiO_p7J/ufTuAM9V3LNKKkw45tYB/Iq8ZAcNuDLdKSEpbjiNX/vE-hq92_0qekhbaAZBYN, stripped
```

I've verified that building tflint with `CGO_ENABLED=0` produces a statically linked binary that should execute in any Linux environment.

I haven't gone super deep, but it looks like the problem is due to the Go compiler defaulting to enabling CGO when not cross-compiling - and as per https://github.com/wata727/tflint/blob/master/.github/workflows/release.yml#L12 goreleaser runs in a linux-amd64 environment - the same GOOS-GOARCH as my Alpine environment 😄. This issue is also described in the Goreleaser issue https://github.com/goreleaser/goreleaser/issues/225.

As far as I can tell the solution may be to disable CGO in goreleaser.

**Comment by craigfurman** [comment]
https://github.com/wata727/tflint/pull/431 might solve this, but as far as I know the only way to verify that is to make a release.

**Comment by wata727** [comment]
@craigfurman Thanks again for the detailed report. This report solved my question that could not be solved for a long time 😄 

v0.11.1 including this patch has been released. This has been verified to work correctly with Alpine Linux:

```
/ # ./tflint -v
TFLint version 0.11.1
/ # file tflint
tflint: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=3R470Aaq9ZS--EuFh_c-/ODDVU-mlNliFxXSPVtTT/jVJgGVVfvczvRatfbcb6/BpjCrGNspdcomKRDew4U, stripped
```

If you still have problems, reopen the issue or open a new one. Thank you!
