### ISSUE TITLE
Switches to enable optional rules from command line

### ISSUE THREAD

**Issue by abitrolly** [wata727/tflint#438]
I've noticed that some [Terraform rules](https://github.com/wata727/tflint/tree/master/docs/rules#terraform-rules) are not enabled by default and I could not find a switch like `--full` to try these rules on my repo.

**Comment by wata727** [comment]
There are currently no options to enable rules from the command line. Options like `--enable-rule` are probably useful.

**Comment by abitrolly** [comment]
Thanks!
```
$ ./tflint --enable-rule terraform_dash_in_resource_name --enable-rule terraform_documented_outputs --enable-rule terraform_documented_variables
$ echo $?
0
```

**Comment by abitrolly** [comment]
I would enable `terraform_dash_in_resource_name` by default.
