### ISSUE TITLE
Support `terraform.tfvars`

### ISSUE THREAD

**Issue by wata727** [wata727/tflint#45]

**Comment by frezbo** [comment]
tfvars should be supported, as it;s a best practice not to have values inside variables.tf and tfvars are not pushed to a vcs. tflint passes witout any errors if I give wrong values in tfvars

**Comment by wata727** [comment]
OK. I'll support this as soon as possible.

**Comment by wata727** [comment]
Hi @frezbo, TFLint 0.3.1 including this feature has been released. Please try it!

**Comment by frezbo** [comment]
Great, @wata727 thanks fir actively maintaining the repo.
