### ISSUE TITLE
Switch to hcl v2 from hcl2

### ISSUE THREAD

**Issue by wata727** [wata727/tflint#473]
See https://github.com/hashicorp/terraform/pull/22982

We also need this migration.

**Comment by ashemedai** [comment]
Just to verify, I know you don't have any azure rules yet, but I should at least get some other rule checks, like the dash/underscore resource name one. Could being fully Terraform 0.12-enabled be the reason tflint 0.12.0 is not showing any error at the moment for my files?

**Comment by wata727** [comment]
> I should at least get some other rule checks, like the dash/underscore resource name one

Does this mean [`terraform_dash_in_resource_name`](https://github.com/wata727/tflint/blob/v0.12.0/docs/rules/terraform_dash_in_resource_name.md) rule ? This rule is currently disabled by default and will not report issues unless enabled.

By the way, it seems that the contents are not related to this issue, so please open another issue or comment on the related issue.

**Comment by ashemedai** [comment]
@wata727 Yes, it did. Sorry for being unclear. That actually worked for what I needed, so no need for additional issues.
