### ISSUE TITLE
When reading from .aws/credentials file any profile other than default produces error

### ISSUE THREAD

**Issue by frezbo** [wata727/tflint#70]
This is my .tflint.hcl file
```
config {
  deep_check = true

  aws_credentials = {
    profile = "master"
    region     = "us-east-1"
  }
}
```

I have no default profile set in .aws/credentials and I have  multiple profiles in the file. Any profile other than default produces this error

```
[ERROR] NoCredentialProviders: no valid providers in chain. Deprecated. 
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

**Comment by wata727** [comment]
Currently, TFLint does not support shared credentials...
Perhaps it should be better to use the credentials specified in Terraform's `provider`.
I plan to support this feature as soon as possible.

**Comment by frezbo** [comment]
@wata727 great thanks, mostly i use env variables so that support should be great. Thanks

**Comment by wata727** [comment]
Hi @frezbo, TFLint v0.3.3 has been released. This version support shared credentials. Please check [README](https://github.com/wata727/tflint#shared-credentials) for details.
Implementation to parse Terraform's `provider` is not done yet. Please wait a moment.

**Comment by frezbo** [comment]
@wata727 great thanks for keeping up-to-date
