### ISSUE TITLE
Allow setting shared credentials path

### ISSUE THREAD

**Issue by smaslennikov** [wata727/tflint#85]
It would be extremely useful to be able to set the shared credentials path (default and the only acceptable by tflint is ~/.aws/credentials). In my specific usecase, Jenkins has a secret file with AWS credentials that simply can't be at that location, but I do receive an environment variable with its location.

To be clear, it's an option to create another, tflint-specific, secret Jenkins file with the credentials but that would be a duplication effort I'd prefer to avoid.

I've never touched Go, but can probably put together a working pull request for this. 

Additionally, is there any reason that the region isn't being parsed out of the credentials file as well? It seems I have to either specify it on command line or via .tflint.hcl.

Thank you!

**Comment by wata727** [comment]
Thanks for your feedback :)

>  it's an option to create another, tflint-specific, secret Jenkins file with the credentials but that would be a duplication effort I'd prefer to avoid.

You're right. I'm just considering an implementation that interprets the Terraform `provider` section.
However, it need the big changes, so I have not started implementing yet.

> is there any reason that the region isn't being parsed out of the credentials file as well?

TFLint supports only shared credentials (`~/.aws/credentials`) , not configuration file (`~/.aws/config`).
The region can only be written in configuration file, so you need to specify it separately.

**Comment by smaslennikov** [comment]
>TFLint supports only shared credentials (~/.aws/credentials) , not configuration file (~/.aws/config).
The region can only be written in configuration file, so you need to specify it separately.

Ahhhhh, that all makes absolute sense. 

For the record, I actually found a better way to deal with all this: In `Jenkinsfile` I have the following wrapping for all tflint usage:
```code
withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'aws-jenkins', usernameVariable: 'AWS_ACCESS_KEY_ID', passwordVariable: 'AWS_SECRET_ACCESS_KEY']]) { }
```

In the credentials plugin, I put in the access key as username and secret key as the password. Works great! I also set the region as an environment variable, and when it's different the project has a `.tflint.hcl` in its directory that overrides it.

I still see some use from specifying the location of the credentials file, but this works well enough.

Again, thanks for your work!
