### ISSUE TITLE
overrides for source cause failure

### ISSUE THREAD

**Issue by LudwigHoff** [wata727/tflint#86]
Hi @wata727 

we use overrides (https://www.terraform.io/docs/configuration/override.html) quite extensively - because it suits our CI/CD tooling - but this causes issues for TFlint...

-- main.tf
module "foo" {
  a = "b"
  c = "d"
}

-- main_override.tf
module "foo" {
    source = "git::http://some_git_url.git?ref=master"
}

I get:
ERROR: Invalid module source in foo

Thanks again for the lovely TFlint tool.  We love it.
N

**Comment by wata727** [comment]
Thank you for using TFLint!

Unfortunately, it does not support overrides yet...
I'll proceed with development to support this feature :)

**Comment by wata727** [comment]
Hi @LudwigHoff. I have been released TFLint v0.4.0 that support overrides! Please try it :)

**Comment by LudwigHoff** [comment]
I surely shall.  Thank you.

**Comment by LudwigHoff** [comment]
Sorry @wata727 I completely forgot to post.  This is grand.  Thanks again
